### ISSUE TITLE
Capitalization problem with composer autoloader

### ISSUE THREAD

**Issue by redcuillin** [Jeremy-Vaud/gfonts-downloader#1]
Using gfonts-downloader as specified in a Linux environment I find I get fatal errors:

`PHP Fatal error:  Uncaught Error: Class "GFontsDownloader\GFontsDownloader\GFontsDownloader" not found in /path/to/fontdownloader.php:14`

The problem is due to the capitalization of files in the Composer directories. Composer expects the filename and class to have the same capitalization, therefore `vendor/gfontsdownloader/gfontsdownloader/src/gfontsdownloader.php` will not load because called classname is GFontsDownloader\GFontsDownloader\GFontsDownloader.

Changing gfontsdownloader.php to GFontsDownloader.php solves the problem.

It's possible/probable this isn't an issue on Windows machines.

**Comment by redcuillin** [comment]
I created a pull request with a fix that works for me:

https://github.com/Jeremy-Vaud/gfonts-downloader/pull/2

**Comment by Jeremy-Vaud** [comment]
Yes it wasn't an issue on Windows.
Thank you
